/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicBackfillSentRouteImport } from './routes/api/public/backfill-sent'
import { Route as ApiPublicBackfillCrmRouteImport } from './routes/api/public/backfill-crm'
import { Route as ApiPublicApproveInvoiceRouteImport } from './routes/api/public/approve-invoice'
import { Route as ApiPublicAcceptQuoteRouteImport } from './routes/api/public/accept-quote'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCronQuoteFollowUpRouteImport } from './routes/api/public/cron/quote-follow-up'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackfillSentRoute = ApiPublicBackfillSentRouteImport.update({
  id: '/api/public/backfill-sent',
  path: '/api/public/backfill-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackfillCrmRoute = ApiPublicBackfillCrmRouteImport.update({
  id: '/api/public/backfill-crm',
  path: '/api/public/backfill-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApproveInvoiceRoute = ApiPublicApproveInvoiceRouteImport.update({
  id: '/api/public/approve-invoice',
  path: '/api/public/approve-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAcceptQuoteRoute = ApiPublicAcceptQuoteRouteImport.update({
  id: '/api/public/accept-quote',
  path: '/api/public/accept-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronQuoteFollowUpRoute =
  ApiPublicCronQuoteFollowUpRouteImport.update({
    id: '/api/public/cron/quote-follow-up',
    path: '/api/public/cron/quote-follow-up',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/accept-quote': typeof ApiPublicAcceptQuoteRoute
  '/api/public/approve-invoice': typeof ApiPublicApproveInvoiceRoute
  '/api/public/backfill-crm': typeof ApiPublicBackfillCrmRoute
  '/api/public/backfill-sent': typeof ApiPublicBackfillSentRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/quote-follow-up': typeof ApiPublicCronQuoteFollowUpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/accept-quote': typeof ApiPublicAcceptQuoteRoute
  '/api/public/approve-invoice': typeof ApiPublicApproveInvoiceRoute
  '/api/public/backfill-crm': typeof ApiPublicBackfillCrmRoute
  '/api/public/backfill-sent': typeof ApiPublicBackfillSentRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/quote-follow-up': typeof ApiPublicCronQuoteFollowUpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/accept-quote': typeof ApiPublicAcceptQuoteRoute
  '/api/public/approve-invoice': typeof ApiPublicApproveInvoiceRoute
  '/api/public/backfill-crm': typeof ApiPublicBackfillCrmRoute
  '/api/public/backfill-sent': typeof ApiPublicBackfillSentRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/quote-follow-up': typeof ApiPublicCronQuoteFollowUpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/email/unsubscribe'
    | '/api/public/accept-quote'
    | '/api/public/approve-invoice'
    | '/api/public/backfill-crm'
    | '/api/public/backfill-sent'
    | '/lovable/email/suppression'
    | '/api/public/cron/quote-follow-up'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/email/unsubscribe'
    | '/api/public/accept-quote'
    | '/api/public/approve-invoice'
    | '/api/public/backfill-crm'
    | '/api/public/backfill-sent'
    | '/lovable/email/suppression'
    | '/api/public/cron/quote-follow-up'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/email/unsubscribe'
    | '/api/public/accept-quote'
    | '/api/public/approve-invoice'
    | '/api/public/backfill-crm'
    | '/api/public/backfill-sent'
    | '/lovable/email/suppression'
    | '/api/public/cron/quote-follow-up'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicAcceptQuoteRoute: typeof ApiPublicAcceptQuoteRoute
  ApiPublicApproveInvoiceRoute: typeof ApiPublicApproveInvoiceRoute
  ApiPublicBackfillCrmRoute: typeof ApiPublicBackfillCrmRoute
  ApiPublicBackfillSentRoute: typeof ApiPublicBackfillSentRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronQuoteFollowUpRoute: typeof ApiPublicCronQuoteFollowUpRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backfill-sent': {
      id: '/api/public/backfill-sent'
      path: '/api/public/backfill-sent'
      fullPath: '/api/public/backfill-sent'
      preLoaderRoute: typeof ApiPublicBackfillSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backfill-crm': {
      id: '/api/public/backfill-crm'
      path: '/api/public/backfill-crm'
      fullPath: '/api/public/backfill-crm'
      preLoaderRoute: typeof ApiPublicBackfillCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/approve-invoice': {
      id: '/api/public/approve-invoice'
      path: '/api/public/approve-invoice'
      fullPath: '/api/public/approve-invoice'
      preLoaderRoute: typeof ApiPublicApproveInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/accept-quote': {
      id: '/api/public/accept-quote'
      path: '/api/public/accept-quote'
      fullPath: '/api/public/accept-quote'
      preLoaderRoute: typeof ApiPublicAcceptQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/quote-follow-up': {
      id: '/api/public/cron/quote-follow-up'
      path: '/api/public/cron/quote-follow-up'
      fullPath: '/api/public/cron/quote-follow-up'
      preLoaderRoute: typeof ApiPublicCronQuoteFollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicAcceptQuoteRoute: ApiPublicAcceptQuoteRoute,
  ApiPublicApproveInvoiceRoute: ApiPublicApproveInvoiceRoute,
  ApiPublicBackfillCrmRoute: ApiPublicBackfillCrmRoute,
  ApiPublicBackfillSentRoute: ApiPublicBackfillSentRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronQuoteFollowUpRoute: ApiPublicCronQuoteFollowUpRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
